/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND_BANG = 1,
  aux_sym_shebang_token1 = 2,
  anon_sym_BANG = 3,
  anon_sym_source = 4,
  anon_sym_SEMI = 5,
  anon_sym_EQ = 6,
  anon_sym_DOLLAR = 7,
  anon_sym_L = 8,
  anon_sym_DOT = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  sym_ident = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym_shebang = 15,
  sym__statement = 16,
  sym__expression = 17,
  sym__atom = 18,
  sym_source = 19,
  sym_assignment = 20,
  sym_application = 21,
  sym_variable = 22,
  sym_lambda = 23,
  aux_sym_source_file_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND_BANG] = "#!",
  [aux_sym_shebang_token1] = "shebang_token1",
  [anon_sym_BANG] = "!",
  [anon_sym_source] = "source",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_L] = "L",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_ident] = "ident",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_shebang] = "shebang",
  [sym__statement] = "_statement",
  [sym__expression] = "_expression",
  [sym__atom] = "_atom",
  [sym_source] = "source",
  [sym_assignment] = "assignment",
  [sym_application] = "application",
  [sym_variable] = "variable",
  [sym_lambda] = "lambda",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND_BANG] = anon_sym_POUND_BANG,
  [aux_sym_shebang_token1] = aux_sym_shebang_token1,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_source] = anon_sym_source,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_L] = anon_sym_L,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_ident] = sym_ident,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_shebang] = sym_shebang,
  [sym__statement] = sym__statement,
  [sym__expression] = sym__expression,
  [sym__atom] = sym__atom,
  [sym_source] = sym_source,
  [sym_assignment] = sym_assignment,
  [sym_application] = sym_application,
  [sym_variable] = sym_variable,
  [sym_lambda] = sym_lambda,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_shebang_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_source] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_L] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_shebang] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_param = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_param] = "param",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_param, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 10,
  [14] = 7,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 19,
  [26] = 26,
  [27] = 26,
  [28] = 24,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 33,
  [36] = 34,
  [37] = 37,
  [38] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 15,
        '#', 30,
        '$', 19,
        '(', 22,
        ')', 23,
        '.', 21,
        ';', 17,
        '=', 18,
        'L', 20,
        's', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == 's') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == 'c') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '!') ADVANCE(15);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == 'L') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 15,
        '#', 31,
        '$', 19,
        '(', 22,
        ')', 23,
        '.', 21,
        ';', 17,
        '=', 18,
        'L', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_POUND_BANG);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(31);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_shebang_token1);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_shebang_token1);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\r') ADVANCE(13);
      if (lookahead == '#') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_shebang_token1);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(14);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_source);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_L);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(31);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND_BANG] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_source] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_L] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(31),
    [sym_shebang] = STATE(3),
    [sym__statement] = STATE(2),
    [sym__expression] = STATE(6),
    [sym__atom] = STATE(6),
    [sym_assignment] = STATE(2),
    [sym_application] = STATE(6),
    [sym_variable] = STATE(20),
    [sym_lambda] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUND_BANG] = ACTIONS(7),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_ident] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(5),
    [sym__expression] = STATE(6),
    [sym__atom] = STATE(6),
    [sym_assignment] = STATE(5),
    [sym_application] = STATE(6),
    [sym_variable] = STATE(20),
    [sym_lambda] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_ident] = ACTIONS(17),
    [sym_comment] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(4),
    [sym__expression] = STATE(6),
    [sym__atom] = STATE(6),
    [sym_assignment] = STATE(4),
    [sym_application] = STATE(6),
    [sym_variable] = STATE(20),
    [sym_lambda] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_ident] = ACTIONS(17),
    [sym_comment] = ACTIONS(21),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(5),
    [sym__expression] = STATE(6),
    [sym__atom] = STATE(6),
    [sym_assignment] = STATE(5),
    [sym_application] = STATE(6),
    [sym_variable] = STATE(20),
    [sym_lambda] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_ident] = ACTIONS(17),
    [sym_comment] = ACTIONS(21),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(5),
    [sym__expression] = STATE(6),
    [sym__atom] = STATE(6),
    [sym_assignment] = STATE(5),
    [sym_application] = STATE(6),
    [sym_variable] = STATE(20),
    [sym_lambda] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(30),
    [anon_sym_L] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(36),
    [sym_ident] = ACTIONS(39),
    [sym_comment] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_L,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(44), 1,
      sym_ident,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_BANG,
    STATE(27), 3,
      sym__atom,
      sym_variable,
      sym_lambda,
  [25] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_ident,
    STATE(15), 5,
      sym__expression,
      sym__atom,
      sym_application,
      sym_variable,
      sym_lambda,
  [48] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      sym_ident,
    STATE(16), 5,
      sym__expression,
      sym__atom,
      sym_application,
      sym_variable,
      sym_lambda,
  [71] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_ident,
    STATE(17), 5,
      sym__expression,
      sym__atom,
      sym_application,
      sym_variable,
      sym_lambda,
  [94] = 6,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_L,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_ident,
    STATE(11), 5,
      sym__expression,
      sym__atom,
      sym_application,
      sym_variable,
      sym_lambda,
  [117] = 7,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_L,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(44), 1,
      sym_ident,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_BANG,
    STATE(27), 3,
      sym__atom,
      sym_variable,
      sym_lambda,
  [142] = 7,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_ident,
    ACTIONS(60), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
    STATE(26), 3,
      sym__atom,
      sym_variable,
      sym_lambda,
  [167] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      sym_ident,
    STATE(12), 5,
      sym__expression,
      sym__atom,
      sym_application,
      sym_variable,
      sym_lambda,
  [190] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_ident,
    STATE(18), 5,
      sym__expression,
      sym__atom,
      sym_application,
      sym_variable,
      sym_lambda,
  [213] = 7,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_ident,
    ACTIONS(68), 1,
      anon_sym_RPAREN,
    STATE(26), 3,
      sym__atom,
      sym_variable,
      sym_lambda,
  [237] = 7,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_ident,
    ACTIONS(70), 1,
      anon_sym_SEMI,
    STATE(26), 3,
      sym__atom,
      sym_variable,
      sym_lambda,
  [261] = 7,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_ident,
    ACTIONS(72), 1,
      anon_sym_SEMI,
    STATE(26), 3,
      sym__atom,
      sym_variable,
      sym_lambda,
  [285] = 7,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 1,
      anon_sym_L,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_ident,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    STATE(26), 3,
      sym__atom,
      sym_variable,
      sym_lambda,
  [309] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_ident,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_EQ,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
  [324] = 4,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_EQ,
    ACTIONS(84), 1,
      sym_ident,
    ACTIONS(80), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
  [341] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_ident,
    ACTIONS(86), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
  [355] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_ident,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
  [369] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_ident,
    ACTIONS(94), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
  [383] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(100), 1,
      sym_ident,
    ACTIONS(98), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
  [397] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_ident,
    ACTIONS(76), 5,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [411] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_ident,
    ACTIONS(102), 5,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [425] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_ident,
    ACTIONS(102), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
  [439] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(100), 1,
      sym_ident,
    ACTIONS(98), 5,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [453] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_ident,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_DOLLAR,
      anon_sym_L,
      anon_sym_LPAREN,
  [467] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_source,
    STATE(23), 1,
      sym_source,
  [477] = 2,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
  [484] = 2,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_ident,
  [491] = 2,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(116), 1,
      sym_ident,
  [498] = 2,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_DOT,
  [505] = 2,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(120), 1,
      sym_ident,
  [512] = 2,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_DOT,
  [519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      aux_sym_shebang_token1,
  [526] = 2,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 25,
  [SMALL_STATE(8)] = 48,
  [SMALL_STATE(9)] = 71,
  [SMALL_STATE(10)] = 94,
  [SMALL_STATE(11)] = 117,
  [SMALL_STATE(12)] = 142,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 190,
  [SMALL_STATE(15)] = 213,
  [SMALL_STATE(16)] = 237,
  [SMALL_STATE(17)] = 261,
  [SMALL_STATE(18)] = 285,
  [SMALL_STATE(19)] = 309,
  [SMALL_STATE(20)] = 324,
  [SMALL_STATE(21)] = 341,
  [SMALL_STATE(22)] = 355,
  [SMALL_STATE(23)] = 369,
  [SMALL_STATE(24)] = 383,
  [SMALL_STATE(25)] = 397,
  [SMALL_STATE(26)] = 411,
  [SMALL_STATE(27)] = 425,
  [SMALL_STATE(28)] = 439,
  [SMALL_STATE(29)] = 453,
  [SMALL_STATE(30)] = 467,
  [SMALL_STATE(31)] = 477,
  [SMALL_STATE(32)] = 484,
  [SMALL_STATE(33)] = 491,
  [SMALL_STATE(34)] = 498,
  [SMALL_STATE(35)] = 505,
  [SMALL_STATE(36)] = 512,
  [SMALL_STATE(37)] = 519,
  [SMALL_STATE(38)] = 526,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shebang, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [112] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lambda(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lambda",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
